[project]
name = "social-media-stats-tools"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.1",
    "drissionpage~=4.1.1.2",
    "lark-oapi>=1.5.2",
    "loguru~=0.7.3",
    "pandas>=2.3.3",
    "peewee>=3.18.3",
    "pillow>=12.1.0",
    "prefect>=3.6.9",
    "requests~=2.32.5",
    "requests-toolbelt>=1.0.0",
    "sentry-sdk>=2.48.0",
]
